*Notebook created by Mubashshir Ali for the purpose of Climate Risk Assessment lecture*

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#What-is-Python?" data-toc-modified-id="What-is-Python?-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>What is Python?</a></span></li><li><span><a href="#Why-Python?" data-toc-modified-id="Why-Python?-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Why Python?</a></span><ul class="toc-item"><li><span><a href="#Python-in-Science" data-toc-modified-id="Python-in-Science-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Python in Science</a></span></li></ul></li><li><span><a href="#Using-Jupyter-Notebook" data-toc-modified-id="Using-Jupyter-Notebook-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Using Jupyter Notebook</a></span><ul class="toc-item"><li><span><a href="#Use-as-Shell-Terminal" data-toc-modified-id="Use-as-Shell-Terminal-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Use as Shell Terminal</a></span></li></ul></li><li><span><a href="#Variables" data-toc-modified-id="Variables-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Variables</a></span><ul class="toc-item"><li><span><a href="#Assigning-values-to-the-variable" data-toc-modified-id="Assigning-values-to-the-variable-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Assigning values to the variable</a></span><ul class="toc-item"><li><span><a href="#Multiple-assignments" data-toc-modified-id="Multiple-assignments-4.1.1"><span class="toc-item-num">4.1.1&nbsp;&nbsp;</span>Multiple assignments</a></span></li></ul></li></ul></li><li><span><a href="#Standard-Data-Types" data-toc-modified-id="Standard-Data-Types-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Standard Data Types</a></span><ul class="toc-item"><li><span><a href="#Numbers" data-toc-modified-id="Numbers-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Numbers</a></span></li><li><span><a href="#Strings" data-toc-modified-id="Strings-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Strings</a></span><ul class="toc-item"><li><span><a href="#Indexing-and-slicing" data-toc-modified-id="Indexing-and-slicing-5.2.1"><span class="toc-item-num">5.2.1&nbsp;&nbsp;</span>Indexing and slicing</a></span></li></ul></li><li><span><a href="#Lists" data-toc-modified-id="Lists-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Lists</a></span><ul class="toc-item"><li><span><a href="#Indexing-and-Slicing" data-toc-modified-id="Indexing-and-Slicing-5.3.1"><span class="toc-item-num">5.3.1&nbsp;&nbsp;</span>Indexing and Slicing</a></span></li><li><span><a href="#Adding-Strings" data-toc-modified-id="Adding-Strings-5.3.2"><span class="toc-item-num">5.3.2&nbsp;&nbsp;</span>Adding Strings</a></span></li><li><span><a href="#Testing" data-toc-modified-id="Testing-5.3.3"><span class="toc-item-num">5.3.3&nbsp;&nbsp;</span>Testing</a></span></li></ul></li><li><span><a href="#Tuples" data-toc-modified-id="Tuples-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Tuples</a></span></li><li><span><a href="#Python-Dictionaries" data-toc-modified-id="Python-Dictionaries-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Python Dictionaries</a></span><ul class="toc-item"><li><span><a href="#Accessing-keys-and-values" data-toc-modified-id="Accessing-keys-and-values-5.5.1"><span class="toc-item-num">5.5.1&nbsp;&nbsp;</span>Accessing keys and values</a></span></li></ul></li></ul></li><li><span><a href="#Introduction-to-Numpy" data-toc-modified-id="Introduction-to-Numpy-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Introduction to Numpy</a></span><ul class="toc-item"><li><span><a href="#Why-numpy-is-needed?" data-toc-modified-id="Why-numpy-is-needed?-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Why numpy is needed?</a></span></li><li><span><a href="#Creating-Numpy-arrays-from-Python-lists" data-toc-modified-id="Creating-Numpy-arrays-from-Python-lists-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Creating Numpy arrays from Python lists</a></span><ul class="toc-item"><li><span><a href="#Method-1" data-toc-modified-id="Method-1-6.2.1"><span class="toc-item-num">6.2.1&nbsp;&nbsp;</span>Method 1</a></span></li><li><span><a href="#Method-2" data-toc-modified-id="Method-2-6.2.2"><span class="toc-item-num">6.2.2&nbsp;&nbsp;</span>Method 2</a></span></li><li><span><a href="#Method-3" data-toc-modified-id="Method-3-6.2.3"><span class="toc-item-num">6.2.3&nbsp;&nbsp;</span>Method 3</a></span></li></ul></li><li><span><a href="#Multidimensional-arrays" data-toc-modified-id="Multidimensional-arrays-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Multidimensional arrays</a></span></li></ul></li><li><span><a href="#Zen-of-Python-:)" data-toc-modified-id="Zen-of-Python-:)-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Zen of Python :)</a></span></li><li><span><a href="#Supplementary-info" data-toc-modified-id="Supplementary-info-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Supplementary info</a></span><ul class="toc-item"><li><span><a href="#How-to-install-Jupyter-notebooks-on-your-PC" data-toc-modified-id="How-to-install-Jupyter-notebooks-on-your-PC-8.1"><span class="toc-item-num">8.1&nbsp;&nbsp;</span>How to install Jupyter notebooks on your PC</a></span></li></ul></li></ul></div>

In [1]:
from IPython.display import Image
import IPython.display
from IPython.core.display import HTML 

# What is Python?

In [2]:
IPython.display.IFrame("https://en.wikipedia.org/wiki/Python_(programming_language)", width=1000, height=780)

# Why Python?

In [3]:
Image(url= "https://cdn-images-1.medium.com/max/1600/1*JMP0SgtuTAO1A2Mj04qtfw.png")

Source: Stack Overflow

In [4]:
Image(url= "https://cdn-images-1.medium.com/max/800/1*hr4AQ8riFqCrUzncv0SaRA.png")

Souce: “Ranking Programming Languages by GitHub Users” — Ben Frederickson

*  Python was designed for readability, and has some similarities to the English language with influence from mathematics.


* Python uses new lines to complete a command, as opposed to other programming languages which often use semicolons or parentheses.


* Python relies on indentation, using whitespace, to define scope; such as the scope of loops, functions and classes. Other programming languages often use curly-brackets for this purpose.


* Python is a like a glue bringing lot of interdisciplinary work together

## Python in Science

**Unexpected effectiveness of Python in science** - Jake VanderPlas

In [5]:
Image(url="https://image.slidesharecdn.com/pythonfordatascience-151126012608-lva1-app6892/95/why-python-is-better-for-data-science-25-638.jpg?cb=1448502501")

Two versions of python exist Python2 and Python3. We work with Python3. Here you will find more details: https://wiki.python.org/moin/Python2orPython3

# Using Jupyter Notebook

Add a cell below this one and type print("Hello") and run the cell

In [6]:
print("Hello World!")

Hello World!


In [7]:
## can also be used as a simple calculator
60*24

1440

## Use as Shell Terminal

Jupyter notebooks also provide in-built capabilites to display shell commands. Use ! (exclamation mark) in front of a shell command

In [8]:
## Example
!pwd

/home/mali/Documents/CRA_tutorials_2019


# Variables

Python variables can start with a to z or underscore. Variables are *case sensitve*. There are some resevered words that are used as Python keywords (see list included below). You can't use these words for declaring variables. 

In [9]:
## Python Keywords
Image(url="https://i.imgur.com/ROm3pQd.png")

## Assigning values to the variable

In [10]:
a = 10         # integer
b = 100.0      # float
c = 'Climate'  # a string

print(a)

10


With the variables you can do simple arithmetics

In [11]:
print(a+b)

110.0


In [12]:
c

'Climate'

Anything included inside ' ' or " " or """ """ is treated as a string.

### Multiple assignments

In [13]:
## Multiple assignments
a = b = c = 20
b

20

In [14]:
### This works too
a, b, d = 10, 20, 'Climate'
d

'Climate'

**Task:** Calculate the sum of a,b,c and print the result

In [15]:
print(a+b+c)

50


In [16]:
## Your solution goes here

# Standard Data Types

Python has 5 standard data-types:

* Numbers

* Strings

* List

* Tuple

* Dictionary

## Numbers

Python supports three different numerical types:

* int (signed integers)
* float (floating point real values)
* complex numbers

We won't need further details for the scope of this course

## Strings

Strings are represented as set of characters inside quotation marks

In [17]:
var = 'Climate Risk Assessment'
var # prints complete string

'Climate Risk Assessment'

**We can print subset of strings using slice operator given by the syntax var [start_index : end_index: step].**

*Note: end_index is not included*

### Indexing and slicing

In [18]:
var[0] # prints first character
       # Note: index starts from zero

'C'

**Note: Indexing in Python starts with 0**

In [19]:
var[0:7] # prints first character till 6th character
         # Not necessary to specify step

'Climate'

In [20]:
var [8:] # prints 9th character till the end

'Risk Assessment'

**Task**: Calculate length of the string var? 


*Hint*: Use the function len()

In [21]:
len(var)

23

**Task**: Print the last character of var

In [22]:
var[-1]

't'

## Lists

Lists are group of items separated by commas and enclosed with square brackets [ ]. Lists are the most frequent data type in python. The items inside the list can be anything from a number to a string. A list can also be accessed in the same way as we saw above with strings using the slice operator.

In [23]:
clothes = ['shirt', 'top', 'jeans', 'trousers', 'coat']

### Indexing and Slicing

Same syntax as used for strings before 

In [24]:
clothes[1] # index

'top'

In [25]:
## Slicing as we saw for strings before
clothes[:3]

['shirt', 'top', 'jeans']

In [26]:
numbers = [1,2,3,4,5,6,7,8,9,10,11,12]


**Task: Can you print only the odd numbers from the above list?**

In [27]:
print(numbers[::2])

[1, 3, 5, 7, 9, 11]


In [28]:
climate = [2.5, 'seaice', 'glaciers', 1.5] # you can include numbers and strings together


### Adding Strings

You can add two lists by using `+`

In [29]:
climate + clothes

[2.5, 'seaice', 'glaciers', 1.5, 'shirt', 'top', 'jeans', 'trousers', 'coat']

### Testing

Syntax to test if an element belongs to a certain list is similar to writing it in English

In [30]:
'shirt' in clothes # just don't put the question mark at the end (;

True

## Tuples

Tuples are similar to lists in the sense that it's also a group of items but it's enclosed in small brackets ( ) compared to a list. Another important difference with lists is that *tuples are immutable*. That means we can't change the values inside a tuple. 

In [31]:
mini_tuple = (2.5, 'seaice', 'glaciers', 1.5)
mini_tuple

(2.5, 'seaice', 'glaciers', 1.5)

**Indexing works the same way as in lists**

In [32]:
mini_tuple[2] 

'glaciers'

In [33]:
climate[3] = 'melting' # list items are mutable
climate

[2.5, 'seaice', 'glaciers', 'melting']

**Tuples are not mutable!**

In [34]:
mini_tuple[3] = 'melting' # tuples are not mutable

TypeError: 'tuple' object does not support item assignment

Aha! our first error in Python 

## Python Dictionaries

Python dictionaries consist of key-value pairs, like a dictionary book. You can also visualise it kind of like a table. Dictionary are declared with curly brackets { }.

`Syntax`: dict = {key1:value1, key2:value2}

* Key can be any number or string
* Value can be anything

In [35]:
cl = {'climate': 'change', 'zip': 3012}

In [36]:
print (cl) # prints dictionary

{'climate': 'change', 'zip': 3012}


Values can be assigned or accessed using square brackets [ ]

In [37]:
cl['climate']

'change'

### Accessing keys and values 

In [38]:
print (cl.keys())

dict_keys(['climate', 'zip'])


In [39]:
cl.values()

dict_values(['change', 3012])

-----------------------------------------------------------

# Introduction to Numpy

In [40]:
import numpy as np

## Why numpy is needed?

`Numpy` is a library created to ease mathematical calculation in Python and offers fast and high performance computation. It's the most fundamental library for scientific computing/data analysis.

In [41]:
# run this cell
np?

In [42]:
Image(url= "https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png")

## Creating Numpy arrays from Python lists

In [43]:
a = [1,2,3,4,5,6] # normal list or a normal array
# array is commonly referred to as a list of numbers

### Method 1

In [44]:
## to create a numpy array of the above list a just call np.array(a)
b = np.array(a)
## or directly give the list into numpy array function
c = np.array([1,2,3,4,5,6])

In [45]:
print (a)
print (b)
print (c)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


Note: it's hard to tell any difference using the print command. The missing commas is not really a difference and is not important

In [46]:
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


### Method 2

In [47]:
# There are many ways to create arrays
## one of the most often used method is this..
np.arange(0,10,2) # use shift-tab to see the syntax

array([0, 2, 4, 6, 8])

### Method 3

Another useful way to create an array is when we want a given amount of number between a given range

Example: if we need 50 numbers between 0-10

In [48]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

**Task: Lets say we're asked to calculate sum of only odd numbers lying between in 0-100.**

In [49]:
## lets create array of odd numbers between 0-100 using above function
c = np.arange(1, 100, 2)
c

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [50]:
# calculation of sum is as simple as this
c.sum() # another usuage way is np.sum(c)

2500

In [51]:
# we can also calculate mean for example
c.mean()

50.0

In [ ]:
c. # press tab to see the numerous functions available

## Multidimensional arrays

Unlike Python lists, numpy arrays can be multidimensional like a matrix.

In [53]:
np.ones(shape=(3,4)) # creates a 3x4 matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

This allows as to do Linear Algebra calculations

`Numpy` offers huge amount of features which is not possible to cover in this class. But, if I was successful in convincing you to give `Python` a try then I would definetly recommend you to look up some free `Numpy` tutorial online and give it a try. It is very well documented.

[Numpy tutorial from Scipy, the official tool for scientific programming in Python](https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html)

# Zen of Python :)

A collection of software principles that influence the design of Python

In [54]:
>>> import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


# Supplementary info

## How to install Jupyter notebooks on your PC

Step 1: [Install conda](https://www.anaconda.com/distribution/). Download the file and run it. It will automatically install Python along with most commonly used packages. 

You might have to install some of the more specific packages on your own. Most likely, packages like xarray and cartopy need to be install separately.

Step 2: For installing separate packages run the command below after opening an anaconda shell. You can also run the command in a windows/linux/apple shell.

conda install xarray cartopy netCDF4 

These packages should be sufficient to run the code used in this tutorial on your own PC

Step3: After this you can use jupyter notebooks by just typing "jupyter notebook" on your PC. Alternatively, if you prefer graphical user interface then open Anaconda navigator which will open a graphical UI through which you can open Jupyter Notebooks, download and manage your packages, etc.

**Note: We won't be able to provide individual support for personal installation but Google is at your service.**